version: 2
updates:
  - package-ecosystem: npm
    directory: .
    labels:
      - dependencies
      - javascript
      - 'ready to merge'
    schedule:
      interval: daily
      time: '12:00'
    open-pull-requests-limit: 99
  - package-ecosystem: docker
    directory: .
    labels:
      - dependencies
      - docker
      - 'ready to merge'
    schedule:
      interval: daily
      time: '12:00'
    ignore:
      - dependency-name: "node"
        versions: ["13.x", "14.x"]
      - dependency-name: "node"
        versions: ["1.19.x"]
